name: image

on:
  push:
    branches:
      - 'main'

jobs:
  image:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: sapphi-red
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          build-args: COMMIT_HASH=${{ github.sha }}
          tags: ghcr.io/sapphi-red/web-speed-hackathon-2021-mini:latest
